stages:
  - build
  - test
  - dockerize

# TEMPLATES
.build: &build
  stage: build
  script:
      - mkdir build
      - cd build
      - cmake -GNinja -DCMAKE_PREFIX_PATH="/PMS/software/install/xrootd" -DENABLE_PMS_TESTS=ON ../
      - ninja
  needs: []
  artifacts:
    paths:
      - build

.build-docker: &build-docker
  <<: *build
  tags:
      - docker

build-alma9:
  <<: *build-docker
  image: vformato/pms-ci:alma9

build-ubuntu24.04:
  <<: *build-docker
  image: vformato/pms-ci:ubuntu24.04

build-ubuntu22.04:
  <<: *build-docker
  image: vformato/pms-ci:ubuntu22.04

.test: &test
  stage: test
  script:
    - cd build
    - ./testsuite/run_tests

test-alma9:
  <<: *test
  image: vformato/pms-ci:alma9
  needs: ["build-alma9"]

test-ubuntu22.04:
  <<: *test
  image: vformato/pms-ci:ubuntu22.04
  needs: ["build-ubuntu22.04"]

test-ubuntu24.04:
  <<: *test
  image: vformato/pms-ci:ubuntu24.04
  needs: ["build-ubuntu24.04"]


.dockerize-default : &dockerize-default
  stage: dockerize
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  needs: ["test-ubuntu24.04"]
  tags:
    - docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - cp ${DOCKERFILE} Dockerfile
    - docker login --username vformato --password $dockerhubtoken
    - docker build -t vformato/pms:$dockertag .
    - docker push vformato/pms:$dockertag

dockerize-ubuntu24.04-latest:
  <<: *dockerize-default
  variables:
    dockertag: latest
    DOCKERFILE: Dockerfile
  only:
    - master

dockerize-ubuntu24.04-tagged-version:
  <<: *dockerize-default
  variables:
    dockertag: $CI_COMMIT_REF_NAME
    DOCKERFILE: Dockerfile
  only:
    - /^v[0-9]*\.[0-9]*(\.[0-9]*)$/  # ex: v0.1.0
    - /^v[0-9]*\.[0-9]*(_RC[0-9]*)$/ # ex: v1.0_RC1

dockerize-ubuntu24.04-latest-deb:
  <<: *dockerize-default
  variables:
    dockertag: latest-debug
    DOCKERFILE: Dockerfile_debug
  only:
    - master

dockerize-ubuntu24.04-tagged-version-deb:
  <<: *dockerize-default
  variables:
    dockertag: ${CI_COMMIT_REF_NAME}-debug
    DOCKERFILE: Dockerfile_debug
  only:
    - /^v[0-9]*\.[0-9]*(\.[0-9]*)$/  # ex: v0.1.0
    - /^v[0-9]*\.[0-9]*(_RC[0-9]*)$/ # ex: v1.0_RC1
