stages:
  - build
  - dockerize

# TEMPLATES
.build: &build
  stage: build
  script:
      - mkdir build
      - cd build
      - cmake -GNinja -DCMAKE_PREFIX_PATH="/PMS/software/install/mongo-cxx-driver;/PMS/software/install/xrootd" ../
      - ninja
  needs: []

.build-docker: &build-docker
  <<: *build
  tags:
      - docker

build-centos8:
  <<: *build-docker
  image: vformato/pms-ci:centos8

build-ubuntu20.04:
  <<: *build-docker
  image: vformato/pms-ci:ubuntu20.04

dockerize-ubuntu20.04:
  stage: dockerize
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  needs: ["build-ubuntu20.04"]
  tags:
    - docker
  only:
    - master
  variables:
    # DOCKER_HOST: localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    
  script:
    - cp docker/Dockerfile .
    - docker login --username vformato --password $dockerhubtoken
    - docker build -t vformato/pms:latest .
    - docker push vformato/pms:latest
