stages:
  - build
  - test
  - dockerize

# TEMPLATES
.build: &build
  stage: build
  script:
      - mkdir build
      - cd build
      - cmake -GNinja -DCMAKE_PREFIX_PATH="/PMS/software/install/xrootd" -DPMS_ENABLE_TESTS=ON ../
      - ninja
  needs: []
  artifacts:
    paths:
      - build

.build-docker: &build-docker
  <<: *build
  tags:
      - docker

build-alma9:
  <<: *build-docker
  image: vformato/pms-ci:alma9

build-ubuntu24.04:
  <<: *build-docker
  image: vformato/pms-ci:ubuntu24.04

build-ubuntu22.04:
  <<: *build-docker
  image: vformato/pms-ci:ubuntu22.04

.test: &test
  stage: test
  script:
    - cd build
    - ./testsuite/run_tests

test-alma9:
  <<: *test
  image: vformato/pms-ci:alma9
  needs: ["build-alma9"]

test-ubuntu22.04:
  <<: *test
  image: vformato/pms-ci:ubuntu22.04
  needs: ["build-ubuntu22.04"]

test-ubuntu24.04:
  <<: *test
  image: vformato/pms-ci:ubuntu24.04
  needs: ["build-ubuntu24.04"]

dockerize-ubuntu24.04:
  stage: dockerize
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  needs: ["build-ubuntu24.04"]
  tags:
    - docker
  only:
    - master
  variables:
    # DOCKER_HOST: localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    
  script:
    - cp docker/Dockerfile .
    - docker login --username vformato --password $dockerhubtoken
    - docker build -t vformato/pms:latest .
    - docker push vformato/pms:latest
