repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
