FROM vformato/pms-ci:ubuntu24.04 as builder

COPY . /PMS/software/source/PMS

RUN cd /PMS/software/source/PMS && \
    mkdir build && \
    cd build && \
    cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="/PMS/software/install/xrootd" ../ -DCMAKE_INSTALL_PREFIX=/PMS/software/install/PMS && \
    ninja && \
    ninja install


FROM vformato/pms-ci:ubuntu24.04

RUN apt update
RUN apt install -y gdb

COPY --from=builder /PMS/software/install/ /PMS/software/install/

ENTRYPOINT ["gdb", "--ex", "run", "--args", "/PMS/software/install/PMS/bin/PMSOrchestrator"]
